repos:
-   repo: <https://github.com/pre-commit/pre-commit-hooks> #ссылка на репо
    rev: v2.3.0 #версия репозитория
    hooks:
    -   id: detect-private-key #какие hook’и использовать из репо
-   repo: <https://github.com/PyCQA/flake8>
    rev: 6.1.0
    hooks:
    -   id: flake8